/* Q10: Show the total revenue generated by each sales territory.
   Uses: JOIN, SUM, GROUP BY, ORDER BY
   Output: TerritoryName, TotalRevenue */

SELECT  
    ST.Name AS territory,
   sum(SOH.Totaldue) AS Revenue 
FROM sales.SalesTerritory ST 
JOIN Sales.SalesOrderHeader Soh
    ON st.territoryid = SOH.territoryid
GROUP BY ST.NAME
ORDER BY Revenue DESC;
